import React from 'react';
import { Building2, Tag } from 'lucide-react';

export const QuestionBody = React.memo(function QuestionBody({
  question,
  realCompanies
}) {
  return (
    <>
      {/* AI Challenge Banner */}
      {question.isAiGenerated && (
        <div className="mb-4 p-3.5 rounded-lg bg-gradient-to-br from-purple-500/10 to-blue-500/10 border border-purple-500/20 flex items-start gap-2.5">
          <span className="text-xl shrink-0">🤖</span>
          <div>
            <div className="text-xs font-bold text-purple-500 mb-1">
              AI-Generated {question.companyName ? `${question.companyName} Challenge` : 'Challenge'}
            </div>
            <div className="text-[11px] text-muted leading-relaxed">
              This question was generated by AI. It uses real schema tables — try it like any other question!
              No automatic validation — focus on writing correct SQL.
            </div>
          </div>
        </div>
      )}

      {/* Prompt */}
      <div className="text-[15px] leading-relaxed text-text mb-5 font-medium">
        {question.prompt}
      </div>

      {/* Keywords */}
      <div className="flex flex-wrap gap-2 mb-6">
        {/* Dynamic Supabase Companies */}
        {realCompanies.length > 0 && (
          <span key={'comp-group'} className="bg-transparent text-text-secondary text-xs font-medium flex items-center gap-1.5 py-0.5">
            <Building2 size={13} className="text-primary" />
            <span><strong className="text-text font-semibold">Asked in:</strong> {realCompanies.join(', ')}</span>
          </span>
        )}

        {(question.keywords || []).map(kw => {
          // Ignore the local hardcoded fake company tags
          if (kw.startsWith('company:')) {
            return null;
          }
          if (kw.startsWith('topic:')) {
            const topic = kw.split(':')[1];
            return (
              <span key={kw} className="bg-primary-muted text-primary border-none px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1.5">
                <Tag size={13} /> {topic}
              </span>
            );
          }
          return (
            <span key={kw} className="bg-surface-2 border border-border text-text-secondary px-2.5 py-1 rounded-md text-[11px] font-semibold">
              {kw}
            </span>
          );
        })}
      </div>
    </>
  );
});
